name: adn_svg
description: A Flutter package for dynamic styling of SVGs.
version: 1.0.0
homepage: https://github.com/Yves-K/adn_svg
repository: https://github.com/Yves-K/adn_svg

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  xml: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.1