name: adn_svg
description: A Flutter package for dynamic styling of SVGs.
version: 1.0.0
homepage: https://github.com/Yves-K/svg_type
repository: https://github.com/Yves-K/svg_type

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  xml: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.1